# Global Configuration for AIOS

# API Keys Configuration
api_keys:
  openai: ""    # OpenAI API key
  gemini: ""    # Google Gemini API key
  groq: ""      # Groq API key
  anthropic: "" # Anthropic API key
  huggingface:
    auth_token: ""  # HuggingFace auth token
    home: ""        # Optional: HuggingFace models path

# LLM Configuration
llms:
  models:
    # OpenAI Models
    # - name: "gpt-4"
    #   backend: "openai"
    #   max_new_tokens: 1024
    #   temperature: 1.0

    # Google Models
    # - name: "gemini-1.5-pro"
    #   backend: "google"
    #   max_new_tokens: 2048
    #   temperature: 1.0

    # Anthropic Models
    # - name: "claude-3-opus"
    #   backend: "anthropic"
    #   max_new_tokens: 2048
    #   temperature: 1.0

    # HuggingFace Models
    # - name: "meta-llama/Llama-2-70b-chat-hf"
    #   backend: "huggingface"
    #   max_new_tokens: 2048
    #   temperature: 0.7
    #   max_gpu_memory: {"0": "24GB", "1": "24GB"}  # GPU memory allocation
    #   eval_device: "cuda:0"  # Device for model evaluation

    # Ollama Models
    - name: "qwen2.5:7b"
      backend: "ollama"
      max_new_tokens: 1024
      temperature: 1.0
      hostname: "http://localhost:11434" # Make sure to run ollama server

      
  log_mode: "console"

memory:
  memory_limit: 524288 # 512KB
  eviction_k: 3

storage:
  root_dir: "root"
  use_vector_db: true

scheduler:
  log_mode: "console"

agent_factory:
  log_mode: "console"
  max_workers: 64  
  
server:
  host: "localhost"
  port: 8000
